### ISSUE TITLE
Toggle Actuators On/Off in simulate.cc

### ISSUE THREAD

**Issue by cstegel** [google-deepmind/mujoco#1092] opened 2023-10-11 00:20 UTC
**Is your feature request related to a problem? Please describe.**

I have a scene where I control multiple slide and hinge joints using position actuators. To debug this scene, it would be helpful to adjust the controls in simulate.cc's UI and then disable one of the actuators so that force is no longer applied along one of the constraints temporarily. I am not aware of a way to do this in the current simulate.cc UI.

For example, imagine a crane with one actuator that pulls an object up/down and another that pushes it further/closer away. I want to see what happens if I pick the object up, move it further away, then disable the up/down force to see it drop to the ground. 

**Describe the solution you'd like**

I would like a button beside each of the control sliders to enable/disable the actuator:

<img width="251" alt="Screenshot 2023-10-10 at 5 08 39 PM" src="https://github.com/google-deepmind/mujoco/assets/3453535/cb7fd41a-86f4-41a2-b0e7-8400db918598">

(Add a button beside each of these sliders or make it click-able).

**Describe alternatives you've considered**

I know there's a "disable all actuators" button but this disables everything:

<img width="243" alt="Screenshot 2023-10-10 at 5 08 58 PM" src="https://github.com/google-deepmind/mujoco/assets/3453535/80e422ce-ebf1-4eea-8a8d-fe9a334c8267">

 I want to disable some actuators while keeping others active.

**Additional context**

I see the code for creating the control sliders is [here](https://github.com/google-deepmind/mujoco/blob/main/simulate/simulate.cc#L1032) but I can't figure out how to add something that would disable actuators.

**Comment by yuvaltassa** [comment] 2023-10-11 11:22
Duplicate of #1024

Unfortunately disabling actuators at runtime is currently not possible.

I have a draft feature that would add  `<option actuatorgroupdisable/>`, which uses actuator groups to choose which ones to disable. Defaults to `""` (all enabled) and then you could say `<option actuatorgroupdisable="1 3 4">` to mean disable all actuators in some groups.

In terms of UI, this could be tied to a new panel letting you enable/disable at runtime, or this could just use the current group diable panel (although we would need to change the default from only 0 1 2 enabled to all enabled), in this case actuator visualisation would be tied to actuator activation.

The main limitation of this approach would be that only 6 groups of actuators could be enable/disabled at runtime. WOuld that be good enough for you?

**Comment by cstegel** [comment] 2023-10-11 14:58
Hi Yuval,

Thank you for considering this and working on MuJoCo! 

Disabling actuator groups similar to disabling them being rendered works for my use case. I only need to disable a couple different actuators individually so 6 groups should be enough for me.

**Comment by yuvaltassa** [comment] 2023-10-12 17:49
I hope to do this next week. 
Please ping me back here if it hasn't happened by the end of October?

**Closed** 2023-10-31 23:25 UTC
Labels: enhancement

**Comment by yuvaltassa** [comment] 2023-11-01 02:43
https://mujoco.readthedocs.io/en/latest/modeling.html#group-disable
