### ISSUE TITLE
Adoption of type-hints

### ISSUE THREAD

**Issue by priba** [google-deepmind/mujoco#1874] opened 2024-08-02 11:48 UTC
The adoption of type-hints is becoming popular in the python community. Are there plans to add type hints within mujoco?

**Comment by kevinzakka** [comment] 2024-08-02 13:52
See #1292 for a temporary solution.

**Comment by kevinzakka** [comment] 2024-08-15 17:21
Going to close as a duplicate of #1292.

**Closed by kevinzakka** 2024-08-15 17:21 UTC
Labels: enhancement
