### ISSUE TITLE
Suggestion for auto-connect elements

### ISSUE THREAD

**Issue by TenguBoss** [google-deepmind/mujoco#1319] opened 2024-01-08 05:38 UTC
Dear Colleagues,

I have used auto-connect to successfully debug a MuJoCo model. Auto-connect is a great tool but, if I may, I would like to suggest an improvement. 

Would it be possible to make the diameter of the branches (pill geometries?) inversely proportional to the distance from the "root"? In my opinion, the kinematic tree would be easier to debug and analyze. Also it would look like a real tree. 

Thank you.

BU

**Comment by yuvaltassa** [comment] 2024-01-08 09:37
Duplicate of #1307, see that issue for a pointer to the code that implements it. Feel free to modify/improve and send us a PR.

cc @vikashplus

**Closed by yuvaltassa** 2024-01-08 09:37 UTC
Labels: duplicate, enhancement
