### ISSUE TITLE
GUI graphics is not displayed properly

### ISSUE THREAD

**Issue by yzd0014** [google-deepmind/mujoco#1144] opened 2023-10-28 00:11 UTC
![Screenshot 2023-10-27 164541](https://github.com/google-deepmind/mujoco/assets/10913570/6ae0a7bb-d1f2-459b-8cd5-9a5929344977)

After I opened mujoco default visualization tool, somehow some text was cut off. I reinstalled the driver, which doesn't fix the issue. I guess it may be related the graphics library that mujoco, maybe I didn't install the necessary library? Any help will be appreciated, thanks!

**Comment by yuvaltassa** [comment] 2023-10-28 10:53
Do you have an AMD graphics card?
If yes, search the issues for AMD and subscribe to the relevant one. We are working on a fix.

If not, please give more details regarding your setup.

**Comment by saran-t** [comment] 2023-10-28 12:16
The one bit of good news is that your screenshot is pretty much exactly what I saw last week on our AMD machine (7940HS, Adrenalin 23.10.2 driver, Windows 11 Pro), so it's the most likely one to get fixed. 

Otherwise I'll close this as a duplicate of #639. Let's continue discussions there.

**Closed by saran-t** 2023-10-28 12:16 UTC
Labels: question

**Comment by yzd0014** [comment] 2023-10-28 16:15
> Do you have an AMD graphics card? If yes, search the issues for AMD and subscribe to the relevant one. We are working on a fix.
> 
> If not, please give more details regarding your setup.

Yes, it's an AMD gpu

**Comment by yzd0014** [comment] 2023-10-28 16:16
> The one bit of good news is that your screenshot is pretty much exactly what I saw last week on our AMD machine (7940HS, Adrenalin 23.10.2 driver, Windows 11 Pro), so it's the most likely one to get fixed.
> 
> Otherwise I'll close this as a duplicate of #639. Let's continue discussions there.

Thanks for confirming that it's an issue related to AMD gpu.
