### ISSUE TITLE
Not displaying flexcomp objects in scene nor raising errorr

### ISSUE THREAD

**Issue by Nick20500** [google-deepmind/mujoco#2136] opened 2024-10-11 21:17 UTC
### Intro

Hi!

I am a undergrad student at ETH Zurich, I use MuJoCo for my research on Multimaterial deformable objects.

### My setup

I use MuJoCo 3.2.3 with python bindings.

### What's happening? What did you expect?

I am currently trying to run my simulation, which I ran successfully with mujoco, now with mjx.
The python script in the attached zip folder
[zip folder mjx_bug_files.zip](https://github.com/user-attachments/files/17347477/mjx_bug_files.zip)
 will run the simulation for 5 seconds and produce frames for a video of 24 fps. In the end, all the generated frames get stitched together to a mp4 file.

I expect the output to be a red bottle and a green sphere droping from the heigth of 5 units. (e.g. in the picture generated from running the simulation only with mujoco)
![image](https://github.com/user-attachments/assets/bd8aaa38-d44e-47c6-9ddb-9c282b588b39)

What I get, is only the green sphere (e.g. in the picture)
![image](https://github.com/user-attachments/assets/bf73280c-988a-40bc-9ae7-dde0067d3154)

The only reasonable expleantion for me, is that flexcomps aren't yet supported in mjx. But if this is true, then there should be an error raised.

### Steps for reproduction

1. Download the zip folder
2. unzip the downloaded zip folder and open the folder
3. run the python script "simulate_object_drop_mjx_parallel.py"
3b. if necessary, download the used librarys with "pip install *"
4. see my results

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment] 2024-10-14 10:28
The second error will be fixed soon and it's the same as #2135 hopefully the error message will tell you what the issue is.

**Comment by Nick20500** [comment] 2024-10-14 12:13
> The first error is due to the fact that as you correctly anticipated, flex is not available in MJX.

@quagla Will flex be available in MJX in the near future?

**Comment by quagla** [comment] 2024-10-14 16:05
It's not a priority at the moment I'm afraid.

**Closed** 2024-10-15 08:33 UTC
Labels: bug
