### ISSUE TITLE
Toolbar/buttons disappear after starting mujoco

### ISSUE THREAD

**Issue by owenchen0408** [google-deepmind/mujoco#1761] opened 2024-06-27 05:25 UTC
Hi everyone, I am new to Mujoco. I am trying to run some example models on Mujoco. However, the tool bar disappears after 1 second of opening the GUI. Im using windows and ver 3.1.6
Here is a image if the GUI after the buttons/tool bar disappeared. I think this has to do with a zoom of the GUI. how can I solve this or is this abug? I didn't do any action before the tool bar or buttons disapear
![image](https://github.com/google-deepmind/mujoco/assets/37533130/2e528a1b-c35e-4273-9856-1ccd261ab8a3)

Thanks!

**Comment by yuvaltassa** [comment] 2024-06-27 10:29
What GPU do you have?

**Comment by owenchen0408** [comment] 2024-06-27 11:04
AMD RX 6800M

**Comment by yuvaltassa** [comment] 2024-06-27 11:13
duplicate of #639, there is an ongoing issue with AMD GPUs

**Closed** 2024-06-27 11:13 UTC
Labels: bug, duplicate
