### ISSUE TITLE
Python mjSpec recompilation

### ISSUE THREAD

**Issue by jdao913** [google-deepmind/mujoco#1822] opened 2024-07-17 22:44 UTC
Hello Mujoco team,

Loading and compiling a model and then adding a lone geom directly to the world body and then recompiling does not work with the new mjSpec in Python. 

Following some examples from the [`spec_tests.py`](https://github.com/google-deepmind/mujoco/blob/main/python/mujoco/specs_test.py#L147) file the following works:
```
spec = mj.MjSpec()
spec.compile()
geom = spec.worldbody.add_geom()
geom.name = 'my_geom'
geom.size[0] = 1
geom.pos = [1, 1, 0]
spec.compile()
```
but when first loading a spec from a xml or a string things do not work 
```
model_string = """
    <mujoco>
        <worldbody>
            <body>
                <freejoint/>
                <geom size=".15" mass="1" type="sphere"/>
            </body>
        </worldbody>
    </mujoco>
"""

spec = mj.MjSpec()
spec.from_string(model_string)
spec.compile()
geom = spec.worldbody.add_geom()
geom.name = 'my_geom'
geom.size[0] = 1
geom.pos = [1, 1, 0]
spec.compile()
```

Gives me the following error:
```
ValueError: Error: incompatible id in geom array, position 1
Element name '', id 0, line 6
```
Note that `spec.recompile` does not work either, in this case I get a `mj_setPtrData: mjData buffer size mismatch` error.
Is this intended? Looking the mjSpec Python tests it seems like none of the test cases preloads a xml and then adds a geom. 
 
Adding a body first and then a geom to that body does work, for example the following as no issues:
```
model_string = """
    <mujoco>
        <worldbody>
            <body>
                <freejoint/>
                <geom size=".15" mass="1" type="sphere"/>
            </body>
        </worldbody>
    </mujoco>
"""

spec = mj.MjSpec()
spec.from_string(model_string)
spec.compile()
body = spec.worldbody.add_body()
body.pos = [1, 2, 3]
body.quat = [0, 1, 0, 0]
geom = body.add_geom()
geom.name = 'my_geom'
geom.size[0] = 1
geom.pos = [1, 1, 0]
spec.compile()
```

On a separate note it seems like mjSpec recompilation in Python does not happen in place? As in the `test_recompile` test in the [`spec_tests.py`](https://github.com/google-deepmind/mujoco/blob/main/python/mujoco/specs_test.py#L147) it seems like recompile has to be used like
```
model_new, data_new = spec.recompile(model, data)
```
as opposed to just
```
spec.recompile(model, data)
```
and the `model` and `data` being updated accordingly. This is what I thought would happen based off of the [mj_recompile](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-recompile) documentation, but it seems like this is not that case. 

Is this intended and just a product of having to deal with Python jank or can the recompilation be made in place in the future?

Thank you,
Jeremy

**Comment by JewelryForge** [comment] 2024-07-18 13:16
A c++ program can also reproduce this bug.
```c++

  static constexpr char xml[] = R"(<mujoco>
        <worldbody>
            <body name="my_body">
                <freejoint/>
                <geom name="my_geom1" size=".15" mass="1" type="sphere"/>
            </body>
        </worldbody>
    </mujoco>
  )";

  auto *spec = mj_parseXMLString(xml, nullptr, nullptr, 0);
  auto *model1 = mj_compile(spec, nullptr);  // compile the first time

  auto *world = mjs_findBody(spec, "world");
  auto *geom = mjs_addGeom(world, nullptr);
  mjs_setString(geom->name, "my_geom2");
  geom->size[0] = 1;
  auto *model2 = mj_compile(spec, nullptr);  // compile the second time
  std::cout << mjs_getError(spec) << std::endl;
```

However, if the `spec` is only compiled the second time, the bug won't be triggered. This is because the geom "my_geom1" is assigned an `id=0` when compiled for the first time. When compiled for the second time, as the geom "my_geom2" is directly linked to the worldbody, it will be in front of "my_geom1" when doing `mjCModel::ProcessLists()`. 
https://github.com/google-deepmind/mujoco/blob/231d9632cd8ca54e834758f42efd8d7ed4b7ff2a/src/user/user_model.cc#L3401
Now,  "my_geom2" is at index 0 with id -1, and "my_geom1" is at index 1 with id 0. Then the assertion failed.
https://github.com/google-deepmind/mujoco/blob/231d9632cd8ca54e834758f42efd8d7ed4b7ff2a/src/user/user_model.cc#L3119-L3120
So, why this condition is considered unreasonable?

**Closed** 2024-07-22 15:32 UTC
Labels: bug
